package proxy

import (
	"os"
	"path/filepath"
	"testing"
)

// ─────────────── Clash 连接信息自动发现 ───────────────
//
// 用户反馈：「代理功能怎么用？我怎么还得在 config.json 里设置参数、重启才行？
// 这也太难用了，搞简单一点行吗？」
//
// 实测：Clash 的 external-controller 与 secret 都写在它自己的配置里，
// 完全可以自动读出来 —— 用户不该手工填这些东西。

// TestParseClashEndpoint 从 Clash 配置文本解析 API 地址与 secret。
func TestParseClashEndpoint(t *testing.T) {
	txt := `# Generated by Clash Verge
mixed-port: 10808
log-level: info
external-controller: 127.0.0.1:9097
secret: autumn
external-controller-cors:
  allow-private-network: true
`
	ep := ParseClashEndpoint(txt, "")
	if ep.API != "http://127.0.0.1:9097" {
		t.Errorf("API=%q want http://127.0.0.1:9097", ep.API)
	}
	if ep.Secret != "autumn" {
		t.Errorf("Secret=%q want autumn", ep.Secret)
	}
}

// TestParseClashEndpointQuoted 带引号的 secret（YAML 常见写法）也要能解析。
func TestParseClashEndpointQuoted(t *testing.T) {
	txt := "external-controller: 127.0.0.1:9097\nsecret: \"my secret\"\n"
	ep := ParseClashEndpoint(txt, "")
	if ep.Secret != "my secret" {
		t.Errorf("Secret=%q want %q（应去掉引号）", ep.Secret, "my secret")
	}
}

// TestParseClashEndpointNoSecret 无 secret 时留空（本地未设密码的 Clash 也支持）。
func TestParseClashEndpointNoSecret(t *testing.T) {
	txt := "external-controller: 127.0.0.1:9097\n"
	ep := ParseClashEndpoint(txt, "")
	if ep.API != "http://127.0.0.1:9097" {
		t.Errorf("API=%q", ep.API)
	}
	if ep.Secret != "" {
		t.Errorf("无 secret 应为空, got %q", ep.Secret)
	}
}

// TestParseClashEndpointDefaultPort 配置里没有 external-controller 时用默认 9097。
func TestParseClashEndpointDefaultPort(t *testing.T) {
	ep := ParseClashEndpoint("mixed-port: 10808\n", "")
	if ep.API != "http://127.0.0.1:9097" {
		t.Errorf("应回落默认 API, got %q", ep.API)
	}
}

// TestParseClashEndpointFallbackAPI 显式传入的 api 优先（用户手填时尊重其值）。
func TestParseClashEndpointFallbackAPI(t *testing.T) {
	ep := ParseClashEndpoint("external-controller: 127.0.0.1:9097\n", "http://127.0.0.1:9999")
	if ep.API != "http://127.0.0.1:9999" {
		t.Errorf("显式 api 应优先, got %q", ep.API)
	}
}

// TestDiscoverClashEndpointFromDir 从 Verge 目录自动发现端点（读完整配置）。
func TestDiscoverClashEndpointFromDir(t *testing.T) {
	dir := t.TempDir()
	full := filepath.Join(dir, "clash-verge.yaml")
	os.WriteFile(full, []byte("proxies:\nexternal-controller: 127.0.0.1:9097\nsecret: s3cret\n"), 0o600)
	ep, err := DiscoverClashEndpoint(dir, "")
	if err != nil {
		t.Fatal(err)
	}
	if ep.Secret != "s3cret" {
		t.Errorf("Secret=%q want s3cret", ep.Secret)
	}
}

// TestDiscoverClashEndpointMissing 目录里没有配置时用默认值（不报错——本机 Clash 可能未装）。
func TestDiscoverClashEndpointMissing(t *testing.T) {
	dir := t.TempDir()
	ep, err := DiscoverClashEndpoint(dir, "")
	if err != nil {
		t.Fatalf("缺配置不应报错（用默认值即可）: %v", err)
	}
	if ep.API != "http://127.0.0.1:9097" {
		t.Errorf("应回落默认 API, got %q", ep.API)
	}
}
